<?php

namespace AppBundle\Repository;

/**
 * ApiAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiAccessRepository extends \Doctrine\ORM\EntityRepository
{
}
