<?php

namespace AppBundle\Repository;

/**
 * ApiCredentialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiCredentialsRepository extends \Doctrine\ORM\EntityRepository
{
}
