<?php

namespace AppBundle\Repository;

/**
 * ccRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ccRepository extends \Doctrine\ORM\EntityRepository
{
}
