<?php

namespace AppBundle\Repository;

/**
 * lRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lRepository extends \Doctrine\ORM\EntityRepository
{
}
