<?php

namespace AppBundle\Repository;

/**
 * ReportsBlacklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportsBlacklistRepository extends \Doctrine\ORM\EntityRepository
{
}
