<?php

namespace AppBundle\Repository;

/**
 * TrafficSourcesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrafficSourcesRepository extends \Doctrine\ORM\EntityRepository
{
}
