<?php

namespace AppBundle\Repository;

/**
 * TrafficSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrafficSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
