<?php

namespace AppBundle\Repository;

/**
 * URepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class URepository extends \Doctrine\ORM\EntityRepository
{
}
