<?php

namespace AppBundle\Repository;

/**
 * UsersEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
