<?php

namespace AppBundle\Repository;

/**
 * XRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XRepository extends \Doctrine\ORM\EntityRepository
{
}
