# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.datatable.users:
            class: AppBundle\Datatables\UsersEntityDatatable
            parent: sg_datatables.datatable.abstract
    app.common_controller:
            class: AppBundle\Controller\CommonController
    app.system_controller:
            class: AppBundle\Controller\SystemController
    app.settings:
            class: AppBundle\Controller\SettingsController
    app.voluum_api_controller:
            class: AppBundle\Controller\VoluumApiController
    app.zeropark_api_controller:
                class: AppBundle\Controller\ZeroparkApiController
    app.cake_api:
            class: AppBundle\Controller\CakeApiController
    app.exoclick_api:
            class: AppBundle\Controller\ExoClickApiController
    app.campaign_controller:
            class: AppBundle\Controller\CampaignController


#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
