AppBundle\Entity\ApiCredentials:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ApiCredentialsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        voluum:
            type: string
            length: '255'
        zeropark:
            type: string
            length: '255'
        exoclick:
            type: string
            length: '255'
    lifecycleCallbacks: {  }
