AppBundle\Entity\l:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\lRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
