AppBundle\Entity\Settings:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SettingsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        trafficSourceId:
            type: string
            length: '120'
        trafficName:
            type: string
            length: '60'
    lifecycleCallbacks: {  }
